(defparameter *alu-ops* (list))
(defun collect-alu-ops-from-alu_tb-log (logfile)
  (if (probe-file logfile)
  (with-fp-r
	s logfile
	(do ((line (read-line s nil 'end) (read-line s nil 'end)))
	  ((equalp line 'end))
	  (cond
		((pscan "Z(\\S+)(\\s+)=(\\s+)[0,1]+" line)
		 (let ((b (pscan "Z(\\S+)(\\s+)=(\\s+)[0,1]+" line)))
		   (setf b (preplace "=" b " "))
		   (setf b (psplit "\\s+" b))
		   (push b *alu-ops*)
		   ))
		)
	  ))))
(defun write-alu-ops-to-map (mapfile)
  (with-fp-w
	f mapfile
	(format f "~S~%" *alu-ops*)
	))
(let ((l (argv)))
  (do ((k 0 (+ k 1)))
	((>= k (length l)))
	(cond
	  ((and (equalp (nth k l) "--collect-alu-ops-from-log") (nth (+ k 1) l))
	   (collect-alu-ops-from-alu_tb-log (nth (+ k 1) l)))
	  ((and (equalp (nth k l) "--write-alu-ops-to-map") (nth (+ k 1) l))
	   (write-alu-ops-to-map (nth (+ k 1) l)))
	  ((equalp (nth k l) "--print-alu-ops") (format t "~S~%" *alu-ops*))
	  ((equalp (nth k l) "--help")
	   (let ()
		 (format t " --collect-alu-ops-from-log logfile~%")
		 (format t " --print-alu-ops ~%")
		 (format t " --write-alu-ops-to-map mapfile ~%")
		 ))
	  )
	)
  )
